-- Ejecutar conectado como propietario del esquema AUTH en FREEPDB1.
-- Idempotente: conserva usuarios, hashes, roles y relaciones existentes.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
DECLARE
    cantidad NUMBER;
BEGIN
    SELECT COUNT(*) INTO cantidad FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'USUARIOS_OAUTH' AND COLUMN_NAME = 'ESTADO_REGISTRO';
    IF cantidad = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USUARIOS_OAUTH ADD (ESTADO_REGISTRO VARCHAR2(15) DEFAULT ''ACTIVO'' NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO cantidad FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_USUARIOS_OAUTH_ESTADO';
    IF cantidad = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USUARIOS_OAUTH ADD CONSTRAINT CK_USUARIOS_OAUTH_ESTADO CHECK (ESTADO_REGISTRO IN (''ACTIVO'', ''ELIMINADO''))';
    END IF;

    -- Instalar la nueva protección antes de retirar la unicidad global anterior.
    SELECT COUNT(*) INTO cantidad FROM USER_INDEXES WHERE INDEX_NAME = 'UX_USUARIOS_OAUTH_ACTIVO';
    IF cantidad = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_USUARIOS_OAUTH_ACTIVO ON USUARIOS_OAUTH (CASE WHEN ESTADO_REGISTRO = ''ACTIVO'' THEN USERNAME END)';
    END IF;

    FOR restriccion IN (
        SELECT c.CONSTRAINT_NAME FROM USER_CONSTRAINTS c
        JOIN USER_CONS_COLUMNS col ON col.CONSTRAINT_NAME = c.CONSTRAINT_NAME
        WHERE c.TABLE_NAME = 'USUARIOS_OAUTH' AND c.CONSTRAINT_TYPE = 'U'
        GROUP BY c.CONSTRAINT_NAME
        HAVING COUNT(*) = 1 AND MAX(col.COLUMN_NAME) = 'USERNAME'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE USUARIOS_OAUTH DROP CONSTRAINT '
            || DBMS_ASSERT.ENQUOTE_NAME(restriccion.CONSTRAINT_NAME);
    END LOOP;

    -- También contempla un índice único independiente creado antes de la migración.
    FOR indice IN (
        SELECT i.INDEX_NAME FROM USER_INDEXES i
        JOIN USER_IND_COLUMNS col ON col.INDEX_NAME = i.INDEX_NAME
        WHERE i.TABLE_NAME = 'USUARIOS_OAUTH' AND i.UNIQUENESS = 'UNIQUE'
          AND NOT EXISTS (SELECT 1 FROM USER_CONSTRAINTS c WHERE c.INDEX_NAME = i.INDEX_NAME)
        GROUP BY i.INDEX_NAME
        HAVING COUNT(*) = 1 AND MAX(col.COLUMN_NAME) = 'USERNAME'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP INDEX ' || DBMS_ASSERT.ENQUOTE_NAME(indice.INDEX_NAME);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Migracion completada: borrado logico y username unico entre ACTIVOS.');
END;
/
