create table huespedes (
   id_huesped       number(10),
   nombre           varchar2(50) not null,
   apellido_paterno varchar2(50) not null,
   apellido_materno varchar2(50) not null,
   email            varchar2(100) not null,
   telefono         varchar2(10) not null,
   documento        varchar2(30) not null,
   nacionalidad     varchar2(30) not null,
   estado_registro  varchar2(30) not null,
   constraint check_documento
      check ( documento in ( 'CREDENCIAL',
                             'PASAPORTE',
                             'CARTILLA_MILITAR',
                             'CURP' ) ),
   constraint huesped_telefono_chk check ( regexp_like ( telefono,
                                                         '^[0-9]{10}$' ) ),
   constraint check_huesped_estado_registro check ( estado_registro in ( 'ACTIVO',
                                                                         'ELIMINADO' ) )
);

create table habitaciones (
   id_habitacion     number generated by default as identity,
   numero            number not null,
   tipo              varchar2(50) not null,
   precio            decimal(10,2) not null,
   capacidad         number not null,
   estado_habitacion varchar2(15) default 'DISPONIBLE' not null,
   estado_registro   varchar2(15) default 'ACTIVO' not null,
   constraint pk_id_habitacion primary key ( id_habitacion ),
   constraint chk_numero check ( numero > 0 ),
   constraint chk_tipo
      check ( tipo in ( 'SENCILLA',
                        'DOBLE',
                        'SUITE',
                        'ESTANDAR',
                        'DE LUJO' ) ),
   constraint chk_precio check ( precio > 0 ),
   constraint chk_capacidad check ( capacidad > 0 ),
   constraint chk_estado_habitacion
      check ( estado_habitacion in ( 'DISPONIBLE',
                                     'OCUPADA',
                                     'LIMPIEZA',
                                     'MANTENIMIENTO' ) ),
   constraint chk_estado_registro check ( estado_registro in ( 'ACTIVO',
                                                               'ELIMINADO' ) )
);

create table reservas (
   id_reserva      number generated by default as identity,
   id_huesped      number not null,
   id_habitacion   number not null,
   fecha_entrada   date not null,
   fecha_salida    date not null,
   estado_reserva  varchar2(15) default 'CONFIRMADA' not null,
   estado_registro varchar2(15) default 'ACTIVO' not null,
   constraint pk_id_reserva primary key ( id_reserva ),
   constraint chk_fechas check ( fecha_entrada < fecha_salida ),
   constraint chk_estado_reserva
      check ( estado_reserva in ( 'CONFIRMADA',
                                  'EN_CURSO',
                                  'FINALIZADA',
                                  'CANCELADA' ) ),
   constraint chk_res_estado_registro check ( estado_registro in ( 'ACTIVO',
                                                                   'ELIMINADO' ) )
);